name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Test ru
      uses: ./
      with:
        directory: .workflow
        snakefile: .workflow/Snakefile
        args: "--cores 1"
