
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

    - name: Test run
      uses: ./
      with:
        directory: .workflow
        snakefile: .workflow/Snakefile
        args: "--cores 1"
